version: 2

jobs:
  build_and_test:
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: ~/CircleCI/airflow-demo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build docker image
          command: |
            docker build -t dhanu001/airflow-demo .
      - run: 
          name: Test docker image
          command: |
            docker run puckel/docker-airflow version |grep '1.10.9'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test